language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - test/vendor
    - sample/vendor
    - $HOME/.composer/cache

before_script:
  - phpenv config-rm xdebug.ini
  - cd sample
  - 'if [ "$TRAVIS_PHP_VERSION" = "5.4" ]; then rm composer.lock; fi'
  - composer install -n --prefer-source
  - cd ../test
  - 'if [ "$TRAVIS_PHP_VERSION" = "5.4" ]; then rm composer.lock; fi'
  - composer install -n --prefer-source
  - cd ../

script:
 - cd test
 - ./vendor/bin/codecept run

